Pavel const/epi 19 верстка страницы форума
akezhanbexeitov/pac-man pull request #8
Opened 2024-03-13 09:48 UTC by Pavel-Const

- Добавлена страница форума с данными из мока
- Добавлена страница первого топика с данными из мока
- Добавлен компонент модального окна через portal
- Сверстан компонент создания новой темы форума для модального окна
- Добавлена небольшая логика создания коментария в топике

2024-03-14 09:08 UTC, akezhanbexeitov approved these changes

2024-03-14 18:21 UTC, IvanPeleshok requested changes
Добрый день!

Отлично реализовали фичу, видно, что есть хороший опыт

Оставил небольшие комментарии, который предлагаю поправить (они совсем небольшие)

2024-03-14 18:21 UTC, IvanPeleshok commented on packages/client/src/components/Forum/Comment/index.module.scss
> +    box-shadow: inset 6px 6px 2px 0 rgba(255, 255, 255, 0.25);
Если предпочитаете использовать цвета, то предлагаю их использовать везде

2024-03-14 18:21 UTC, IvanPeleshok commented on packages/client/src/components/Forum/CommentCreate/index.module.scss
> +    box-shadow: inset 6px 6px 2px 0 rgba(255, 255, 255, 0.25);
Аналогично, предлагаю посмотреть ещё кейсы ниже

2024-03-14 18:21 UTC, IvanPeleshok commented on packages/client/src/components/Forum/Message/index.tsx
> +                owner="Павел"
На данный момент это моковые данные? Возможно лучше их вынести в переменную, чтобы было проще заменить на стадии интеграции реального флоу

2024-03-14 18:21 UTC, IvanPeleshok commented on packages/client/src/components/Forum/Topic/index.tsx
> +      onClick={() => navigate(ROUTES.FORUM + `/${id}`, { state: { id: id } })}>
Инлайн колбеки достаточно сложно читатать, в особенности, когда компонент объёмный,  а также сложно оптимизировать

Предлагаю заменить на следующую запись:
```
const handleClick = () => {
 ...
}

return (
  <li onClick={handleClick} />

2024-03-14 18:21 UTC, IvanPeleshok commented on packages/client/src/components/ui/Head/index.tsx
> +      <button className={styles.head__back} onClick={() => navigate(route)}>
Аналогично

2024-03-14 18:21 UTC, IvanPeleshok commented on packages/client/src/pages/ForumPage/[id]/index.module.scss
> +    height: 100svh;
Предлагаю обратить внимание на обратную совместимость https://caniuse.com/?search=svh
Если вас устраивает, то нет проблем :)

2024-03-14 18:21 UTC, IvanPeleshok commented on packages/client/src/pages/ForumPage/forumMock.ts
> +]
Предлагаю добавлять отступы, чтобы было более человекочитаемо

2024-03-14 18:21 UTC, IvanPeleshok commented on packages/client/src/typings/types.ts
> +/*
Если не используется, то удаляем [YAGNI](https://www.techtarget.com/whatis/definition/You-arent-gonna-need-it#:~:text=YAGNI%20principle%20(%22You%20Aren',only%20be%20added%20when%20required.))
Либо оставляем содержательный коммент

2024-03-14 18:21 UTC, IvanPeleshok commented on yarn.lock
Возможно стоит закрепить версии либ, чтобы лок файл менялся только при обновлении пакетов в package.json

2024-03-15 05:41 UTC, Pavel-Const commented on packages/client/src/components/Forum/Message/index.tsx
> +                owner="Павел"
эти моки и так лежат в отдельном файле, тут @/pages/ForumPage/forumMock.ts

2024-03-15 06:55 UTC, Pavel-Const commented on yarn.lock
не стал делать т.к. многие версии уже обновились

2024-03-15 09:16 UTC, IvanPeleshok approved these changes
Работа не имеет критических замечания, отлично реализовали фичу
Оставил пару комментов, которые было бы здорово поправить

Поздравляю, апрув! 🎉 

Хорошего дня :)

2024-03-15 09:16 UTC, IvanPeleshok commented on packages/client/src/components/Forum/Message/index.module.scss
> +    box-shadow: 4px 4px 4px 0 rgba(0, 0, 0, 0.25);
Не везде поправили переменные для цветов

2024-03-15 09:16 UTC, IvanPeleshok commented on packages/client/src/components/Forum/Message/index.tsx
> +                owner="Павел"
owner и date захардкожены, так и должно быть?

2024-03-15 09:16 UTC, IvanPeleshok commented on packages/client/src/components/Forum/ModalCreate/index.module.scss
> +    box-shadow: 4px 4px 4px 0 rgba(0, 0, 0, 0.25);
Аналогично, через переменную

2024-03-15 09:16 UTC, IvanPeleshok commented on packages/client/src/components/Forum/Topic/index.module.scss
> +    box-shadow: 6px 6px 2.299999952316284px 0px #ffffff40 inset;
Переменная

2024-03-15 09:16 UTC, IvanPeleshok commented on packages/client/src/components/ui/Modal/Modal.module.scss
> +        background-color: rgba(47, 58, 101, 0.55);
Переменная

2024-03-15 09:16 UTC, IvanPeleshok commented on packages/client/src/pages/ForumPage/index.tsx
> +  const handleClick = () => {
В примере я давал "искусственное" название

Предлагаю назвать следующим образом: openModal
Ниже также есть логика закрытия - closeModal

2024-03-15 12:07 UTC, merged